name: Generate GitHub Stats Card

on:
  workflow_dispatch:
  schedule:
    - cron: "15 18 * * *"

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Generate stats card
        uses: cicirello/user-statistician@v1
        with:
          image-file: assets/github-analytics.svg
          include-title: "true"
          commit-and-push: "true"
          commit-message: "chore: update GitHub analytics card"
          args: "--user Santu-developer --theme dark"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
