name: Generate GitHub Stats Card

on:
  workflow_dispatch:
  schedule:
    - cron: "15 18 * * *"  # daily (UTC)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Generate stats card
        uses: cicirello/user-statistician@v1
        with:
          image-file: assets/github-analytics.svg
          include-title: "true"
          commit-and-push: "true"
          commit-message: "chore: update GitHub analytics card"
          args: "--user Santu-developer --theme dark"

